development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:9c74a06423341888832ab0725d8402a3@spinyfin.redistogo.com:11737/
  channel_prefix: argamebackend_production
